name: motorotam_v2
description: Moto Rotam Mobil App v2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Services
  http: ^0.13.4

  # Google
  google_fonts: ^2.1.0

 # State Managements
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.4

  # Utility
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.1.0
  line_icons: ^2.0.1
  flutter_svg: ^1.1.1+1
  responsive_framework: ^0.2.0
  grock: ^0.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/app_logo/
   - assets/images/icons_img/
   - assets/images/marka_model_img/
   - assets/images/marka_model_img/ktm/250_adventure/
   - assets/images/marka_model_img/ktm/390_adventure/
   - assets/images/marka_model_img/ktm/890_adventure/
   - assets/images/marka_model_img/ktm/890_adventure_r/
   - assets/images/marka_model_img/ktm/duke_125/
   - assets/images/marka_model_img/ktm/duke_250/
   - assets/images/marka_model_img/ktm/duke_390/
   - assets/images/marka_model_img/ktm/duke_890/
   - assets/images/marka_model_img/ktm/superduke_1290_adventure_r/
   - assets/images/marka_model_img/ktm/superduke_1290_adventure_s/
   - assets/images/markalar_logo/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
