import 'package:flutter/material.dart';
import 'package:motorotam_v2/model/motor_model.dart';

class MotorRiverpod extends ChangeNotifier {
  List<MotorModel> motorlar = [];

  void init() {
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/marka_model_img/ktm/duke_125/125_Duke_1.jpg",
        resimLeft: "assets/images/marka_model_img/ktm/duke_125/125_Duke_3.jpg",
        resimRight: "assets/images/marka_model_img/ktm/duke_125/125_Duke_4.jpg",
        tur: "Naked",
        model: 'Duke 125',
        yil: '2022',
        fiyat: '112.900 ₺',
        yildiz: 2.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '124.7 cc',
        motorTork: '12.0 nm',
        motorPower: '15.0',
        motorHiz: '147 km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "300 mm / 230 mm",
        zincir: "520 X-Ring",
        onLastikCap: "110/70 17",
        arkaLastikCap: "150/60 17",
        yukseklik: "830",
        agirlik: "139",
        yakitDeposu: "13.4",
        ortalamaYakit: "2.42 l/100 km",
      ),
    );
      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/ktm/duke_250/250_Duke.jpg",
          resimLeft: "assets/images/marka_model_img/ktm/duke_250/250_Duke_03.jpg",
          resimRight: "assets/images/marka_model_img/ktm/duke_250/250_Duke_04.jpg",
          tur: "Naked",
          model: 'Duke 250',
          yil: '2022',
          fiyat: '103.900 ₺',
          yildiz: 4.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '248.8 cc',
          motorTork: '24.0 nm',
          motorPower: '30.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "300 mm / 230 mm",
          zincir: "520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "146",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.24 l/100 km",
        ),
      );

      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/ktm/duke_390/390_Duke_1.jpg",
          resimLeft: "assets/images/marka_model_img/ktm/duke_390/390_Duke_2.jpg",
          resimRight: "assets/images/marka_model_img/ktm/duke_390/390_Duke_3.jpg",
          tur: "Naked",
          model: 'Duke 390',
          yil: '2022',
          fiyat: '156.490 ₺',
          yildiz: 1.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '370.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/bos.jpg",
        resimLeft: "assets/images/bos.jpg",
        resimRight: "assets/images/bos.jpg",
        tur: "Naked",
        model: 'Duke 890 R',
        yil: '2022',
        fiyat: '190.0 ₺',
        yildiz: 4.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '889.0 cc',
        motorTork: '99.0 nm',
        motorPower: '121.0',
        motorHiz: '147 km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu 2x / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 240 mm",
        zincir: "520 X-Ring",
        onLastikCap: "120/70 17",
        arkaLastikCap: "180/55 17",
        yukseklik: "834",
        agirlik: "166",
        yakitDeposu: "14.0",
        ortalamaYakit: "4.74 l/100 km",
      ),
    );


      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/ktm/duke_890/890_Duke.png",
          resimLeft: "assets/images/marka_model_img/ktm/duke_890/890_Duke_01.png",
          resimRight: "assets/images/marka_model_img/ktm/duke_890/890_Duke_02.png",
          tur: "Naked",
          model: 'Duke 890',
          yil: '2022',
          fiyat: '190.0 ₺',
          yildiz: 4.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '889.0 cc',
          motorTork: '99.0 nm',
          motorPower: '121.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu 2x / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 240 mm",
          zincir: "520 X-Ring",
          onLastikCap: "120/70 17",
          arkaLastikCap: "180/55 17",
          yukseklik: "834",
          agirlik: "166",
          yakitDeposu: "14.0",
          ortalamaYakit: "4.74 l/100 km",
        ),
      );
      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/ktm/superduke_1290_adventure_r/superDuke_1290_r_2.jpg",
          resimLeft: "assets/images/marka_model_img/ktm/superduke_1290_adventure_r/superDuke_1290_r_3.jpg",
          resimRight: "assets/images/marka_model_img/ktm/superduke_1290_adventure_r/superDuke_1290_r_5.jpg",
          tur: "Naked",
          model: 'SuperDuke 1290 R',
          yil: '2022',
          fiyat: '??.?? ₺',
          yildiz: 1.4,
          motorTipi: "2 silindirli, 4 zamanlı, benzin, 75° V",
          motorHacmi: '1301 cc',
          motorTork: '140 nm',
          motorPower: '180',
          motorHiz: '??.?? ₺ km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Krom molibden çelik ana boru",
          onAmortisor: 'WP APEX 48',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu 2x / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 240 mm",
          zincir: "525 X-Ring",
          onLastikCap: "120/70 17",
          arkaLastikCap: "200/55 17",
          yukseklik: "835",
          agirlik: "189",
          yakitDeposu: "16",
          ortalamaYakit: "6.17 l/100 km",
        ),
      );

    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/bos.jpg",
        resimLeft: "assets/images/bos.jpg",
        resimRight: "assets/images/bos.jpg",
        tur: "Naked",
        model: 'SuperDuke 1290 GT',
        yil: '2022',
        fiyat: '496.700 ₺',
        yildiz: 1.4,
        motorTipi: "2 silindir, 4 zamanlı, benzin,75° V",
        motorHacmi: '1301.9 cc',
        motorTork: '141 nm',
        motorPower: '173',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Krom molibden çelik borudan ana boru",
        onAmortisor: 'WP Yarı aktif süspansiyon USD Ø 48 mm',
        arkaAmortisor: "WP Yarı aktif süspansiyon monoshock",
        onFren: "Dört pistonlu 2x / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 240 mm",
        zincir: "525 X-Ring",
        onLastikCap: "120/70 17",
        arkaLastikCap: "200/55 17",
        yukseklik: "835",
        agirlik: "209",
        yakitDeposu: "23 l",
        ortalamaYakit: "5.99 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/bos.jpg",
        resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
        resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
        tur: "Racing",
        model: 'RC 125',
        yil: '2022',
        fiyat: '124.900 ₺',
        yildiz: 1.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '124.7 cc',
        motorTork: '12.0 nm',
        motorPower: '15.0',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "300 mm / 230 mm",
        zincir: "520 X-Ring",
        onLastikCap: "110/70 17",
        arkaLastikCap: "150/60 17",
        yukseklik: "830",
        agirlik: "149",
        yakitDeposu: "13.4",
        ortalamaYakit: "2.42 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/bos.jpg",
        resimLeft: "assets/images/bos.jpg",
        resimRight: "assets/images/bos.jpg",
        tur: "Racing",
        model: 'RC 390',
        yil: '2022',
        fiyat: '176.900 ₺',
        yildiz: 1.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '--.- cc',
        motorTork: '--.0 nm',
        motorPower: '--.0',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 230 mm",
        zincir: "3520 X-Ring",
        onLastikCap: "110/70 17",
        arkaLastikCap: "150/60 17",
        yukseklik: "830",
        agirlik: "---",
        yakitDeposu: "--.-- l",
        ortalamaYakit: "--.-- l/100 km",
      ),
    );

    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/bos.jpg",
        resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
        resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
        tur: "Naked",
        model: '690 SMC R',
        yil: '2022',
        fiyat: '292.400 ₺',
        yildiz: 1.4,
        motorTipi: "-- silindir, 4 zamanlı, benzin",
        motorHacmi: '--.-- cc',
        motorTork: '--.-- nm',
        motorPower: '--.--',
        motorHiz: '-- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX ---',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "--- mm / --- mm",
        zincir: "--- X-Ring",
        onLastikCap: "---/-- --",
        arkaLastikCap: "---/-- 1--7",
        yukseklik: "---",
        agirlik: "---",
        yakitDeposu: "--.--",
        ortalamaYakit: "--.-- l/100 km",
      ),
    );

    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/marka_model_img/ktm/250_adventure/250_adv_1.jpg",
        resimLeft: "assets/images/marka_model_img/ktm/250_adventure/250_adv_2.jpg",
        resimRight: "assets/images/marka_model_img/ktm/250_adventure/250_adv_3.jpg",
        tur: "Adventure",
        model: '250 ADVENTURE',
        yil: '2022',
        fiyat: '123.900 ₺',
        yildiz: 1.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '248.8 cc',
        motorTork: '24.0 nm',
        motorPower: '30.0',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 230 mm",
        zincir: "520 X-Ring",
        onLastikCap: "100/90 19",
        arkaLastikCap: "130/80 17",
        yukseklik: "855",
        agirlik: "156",
        yakitDeposu: "14.5",
        ortalamaYakit: "3.1 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/marka_model_img/ktm/390_adventure/390_adv_4.jpg",
        resimLeft: "assets/images/marka_model_img/ktm/390_adventure/390_adv_5.jpg",
        resimRight: "assets/images/marka_model_img/ktm/390_adventure/390_adv_5.jpg",
        tur: "Adventure",
        model: '390 ADVENTURE',
        yil: '2022',
        fiyat: '181.390 ₺',
        yildiz: 1.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '373.2 cc',
        motorTork: '37 nm',
        motorPower: '44.0',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 230 mm",
        zincir: "520 X-Ring",
        onLastikCap: "100/90 19",
        arkaLastikCap: "130/80 17",
        yukseklik: "855",
        agirlik: "158",
        yakitDeposu: "14.5",
        ortalamaYakit: "3.37 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/marka_model_img/ktm/890_adventure/890_Adv_01.jpg",
        resimLeft: "assets/images/marka_model_img/ktm/890_adventure/890_Adv_09.jpg",
        resimRight: "assets/images/marka_model_img/ktm/890_adventure/890_Adv_08.jpg",
        tur: "Adventure",
        model: '890 ADVENTURE',
        yil: '2022',
        fiyat: '329.400 ₺',
        yildiz: 1.4,
        motorTipi: "2 silindir, 4 zamanlı, benzin",
        motorHacmi: '889 cc',
        motorTork: '100 nm',
        motorPower: '105.0',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP APEX 43',
        arkaAmortisor: "WP APEX Monoshock",
        onFren: "Dört pistonlu 2x / Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 260 mm",
        zincir: "520 X-Ring",
        onLastikCap: "90/90 21",
        arkaLastikCap: "150/70 18",
        yukseklik: "850",
        agirlik: "196",
        yakitDeposu: "20 l",
        ortalamaYakit: "4.5 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/bos.jpg",
        resimLeft: "assets/images/bos.jpg",
        resimRight: "assets/images/bos.jpg",
        tur: "Adventure",
        model: '890 ADVENTURE R',
        yil: '2022',
        fiyat: '181.390 ₺',
        yildiz: 1.4,
        motorTipi: "2 silindir, 4 zamanlı, benzin",
        motorHacmi: '370.9 cc',
        motorTork: '100 nm',
        motorPower: '105',
        motorHiz: '--- km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Çelik borulardan ana boru",
        onAmortisor: 'WP XPLOR-USD, Ø 48 mm',
        arkaAmortisor: "XACT WP PDS mono shock",
        onFren: "Dört pistonlu 2x/ Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 260 mm",
        zincir: "520 X-Ring",
        onLastikCap: "90/90 21",
        arkaLastikCap: "150/70 18",
        yukseklik: "880",
        agirlik: "196",
        yakitDeposu: "20 l",
        ortalamaYakit: "4.5 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/marka_model_img/ktm/superduke_1290_adventure_s/superDuke_1290_s_1.jpg",
        resimLeft: "assets/images/marka_model_img/ktm/superduke_1290_adventure_s/superDuke_1290_s_4.jpg",
        resimRight: "assets/images/marka_model_img/ktm/superduke_1290_adventure_s/superDuke_1290_s_5.jpg",
        tur: "Adventure",
        model: '1290 ADVENTURE S',
        yil: '2022',
        fiyat: '474.600 ₺',
        yildiz: 1.4,
        motorTipi: "2 silindir, 4 zamanlı, benzin",
        motorHacmi: '1301 cc',
        motorTork: '159 nm',
        motorPower: '159.0',
        motorHiz: '147 km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Krom molibden çelik borudan ana boru",
        onAmortisor: 'WP Semi-Active',
        arkaAmortisor: "WP Semi-Active",
        onFren: "Dört pistonlu 2x/ Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 267 mm",
        zincir: "525 X-Ring",
        onLastikCap: "120/70 19",
        arkaLastikCap: "170/60 17",
        yukseklik: "849 mm",
        agirlik: "220",
        yakitDeposu: "23 l",
        ortalamaYakit: "5.7 l/100 km",
      ),
    );
    motorlar.add(
      MotorModel(
        marka: 'KTM',
        isFavorite: false,
        resim: "assets/images/marka_model_img/ktm/superduke_1290_adventure_r/superDuke_1290_r_2.jpg",
        resimLeft: "assets/images/marka_model_img/ktm/superduke_1290_adventure_r/superDuke_1290_r_5.jpg",
        resimRight: "assets/images/marka_model_img/ktm/superduke_1290_adventure_r/superDuke_1290_r_4.jpg",
        tur: "Adventure",
        model: '1290 ADVENTURE R',
        yil: '2022',
        fiyat: '496.700 ₺',
        yildiz: 1.4,
        motorTipi: "1 silindir, 4 zamanlı, benzin",
        motorHacmi: '1301 cc',
        motorTork: '138 nm',
        motorPower: '159',
        motorHiz: '147 km/h',
        sanziman: "Sıralı, 6 vites",
        debriyaj: "PASC kaydırmalı debriyaj",
        sogutma: "Sıvı soğutma",
        atesleme: 'Bosch EMS',
        sasiTipi: "Krom molibden çelik borudan ana boru",
        onAmortisor: 'WP X-Plor 48 mm',
        arkaAmortisor: "WP Pds monoshock",
        onFren: "Dört pistonlu 2x/ Disk fren",
        arkaFren: "Tek pistonlu / Disk fren",
        frenDiskCap: "320 mm / 267 mm",
        zincir: "525 X-Ring",
        onLastikCap: "120/70 21",
        arkaLastikCap: "170/60 18",
        yukseklik: "880",
        agirlik: "221",
        yakitDeposu: "23 l",
        ortalamaYakit: "5.7 l/100 km",
      ),
    );
  }
}
