import 'package:flutter/material.dart';
import 'package:motorotam_v2/model/motor_model.dart';

class MotorRiverpod extends ChangeNotifier {
  List<MotorModel> motorlar = [];

  void init() {
      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/250_Duke.jpeg",
          resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
          resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
          model: 'KTM Duke 250',
          yil: '2022',
          fiyat: '154.0 ₺',
          yildiz: 3.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '249.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );

      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/250_Duke.jpeg",
          resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
          resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
          model: 'KTM Duke 390',
          yil: '2022',
          fiyat: '190.0 ₺',
          yildiz: 1.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '370.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );

      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/250_Duke.jpeg",
          resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
          resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
          model: 'KTM Duke 690',
          yil: '2022',
          fiyat: '190.0 ₺',
          yildiz: 1.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '370.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );
      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/250_Duke.jpeg",
          resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
          resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
          model: 'KTM Duke 790',
          yil: '2022',
          fiyat: '190.0 ₺',
          yildiz: 1.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '370.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );
      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/250_Duke.jpeg",
          resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
          resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
          model: 'KTM Duke 890',
          yil: '2022',
          fiyat: '190.0 ₺',
          yildiz: 1.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '370.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );
      motorlar.add(
        MotorModel(
          marka: 'KTM',
          isFavorite: false,
          resim: "assets/images/marka_model_img/250_Duke.jpeg",
          resimLeft: "assets/images/marka_model_img/250_Duke.jpeg",
          resimRight: "assets/images/marka_model_img/250_Duke.jpeg",
          model: 'KTM Duke 1290',
          yil: '2022',
          fiyat: '190.0 ₺',
          yildiz: 1.4,
          motorTipi: "1 silindir, 4 zamanlı, benzin",
          motorHacmi: '370.9 cc',
          motorTork: '28.0 nm',
          motorPower: '31.0',
          motorHiz: '147 km/h',
          sanziman: "Sıralı, 6 vites",
          debriyaj: "PASC kaydırmalı debriyaj",
          sogutma: "Sıvı soğutma",
          atesleme: 'Bosch EMS',
          sasiTipi: "Çelik borulardan ana boru şasi, toz kaplama",
          onAmortisor: 'WP APEX 43',
          arkaAmortisor: "WP APEX Monoshock",
          onFren: "Dört pistonlu / Disk fren",
          arkaFren: "Tek pistonlu / Disk fren",
          frenDiskCap: "320 mm / 230 mm",
          zincir: "3520 X-Ring",
          onLastikCap: "110/70 17",
          arkaLastikCap: "150/60 17",
          yukseklik: "830",
          agirlik: "149",
          yakitDeposu: "13.4",
          ortalamaYakit: "3.46 l/100 km",
        ),
      );
  }
}
